apiVersion: v1
kind: Service
metadata:
  name: angular-app-service
spec:
  type: NodePort
  selector:
    app: devopsfinal-app
  ports:
    - protocol: TCP
      port: 9081
      targetPort: 9098
      nodePort: 30097  # Change if needed
